version: 2
updates:
  # Enable version updates for npm (web app)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "your-github-username"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      testing:
        patterns:
          - "*jest*"
          - "*testing*"
          - "@types/*jest*"
      build-tools:
        patterns:
          - "vite*"
          - "typescript"
          - "eslint*"
          - "prettier*"
  
  # Enable version updates for npm (mobile app)
  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "your-github-username"
    commit-message:
      prefix: "chore(mobile-deps)"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      expo:
        patterns:
          - "expo*"
          - "@expo/*"
      react-native:
        patterns:
          - "react-native*"
          - "@react-native*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"