name: CI/CD - Mobile App (Expo)

on:
  push:
    branches: [main, develop]
    paths:
      - 'mobile/**'
      - 'shared/**'
  pull_request:
    branches: [main]
    paths:
      - 'mobile/**'
      - 'shared/**'

jobs:
  test:
    name: Test & Lint Mobile
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: mobile
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json
      
      - name: Setup Expo CLI
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            mobile/node_modules
          key: ${{ runner.os }}-mobile-${{ hashFiles('mobile/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-mobile-
      
      - name: Install dependencies
        run: npm ci
      
      - name: TypeScript check
        run: npx tsc --noEmit
      
      - name: Expo doctor check
        run: npx expo doctor

  preview:
    name: EAS Update Preview
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    
    defaults:
      run:
        working-directory: mobile
    
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "⚠️ You must provide an EXPO_TOKEN secret"
            echo "Create it at: https://expo.dev/settings/access-tokens"
            exit 1
          fi
      
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json
      
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create preview
        id: preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --branch=pr-${{ github.event.number }} --message="PR #${{ github.event.number }}: ${{ github.event.pull_request.title }}"
          working-directory: mobile

  build:
    name: EAS Build
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    defaults:
      run:
        working-directory: mobile
    
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "⚠️ You must provide an EXPO_TOKEN secret for EAS builds"
            echo "Create it at: https://expo.dev/settings/access-tokens"
            exit 1
          fi
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json
      
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build for Android (Preview)
        run: |
          eas build --platform android --profile preview --non-interactive --wait
      
      - name: Build for iOS (Preview) 
        run: |
          eas build --platform ios --profile preview --non-interactive --wait

  submit:
    name: Submit to App Stores
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[submit]')
    
    defaults:
      run:
        working-directory: mobile
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json
      
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Submit to Google Play (Internal Testing)
        run: |
          eas submit --platform android --profile internal --non-interactive
      
      - name: Submit to Apple App Store (TestFlight)
        run: |
          eas submit --platform ios --profile internal --non-interactive